name: Test

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
  schedule:
    - cron: '0 0 * * *'

env:
  GEAR_VERSIONS: 0.1.6 0.1.5 0.1.4 0.1.3 0.1.2 0.1.1
  VARA_VERSIONS: 1.1 1.0

jobs:
  test:
    name: Test formulae
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            unimplemented: true # TODO: Remove after adding support for Linux

          - os: macOS-latest
            unimplemented: false # TODO: Remove after adding support for Linux

    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.unimplemented }} # TODO: Remove after adding support for Linux

    steps:
      - name: Install brew on Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh | bash
          echo "/home/linuxbrew/.linuxbrew/bin" >> $GITHUB_PATH
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          (echo; echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"') >> $HOME/.bash_profile
          (echo; echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"') >> $HOME/.profile
          brew install hello

      # TODO: Find a solution to add a tap from a PR's branch
      - name: Add Gear tap from PR's branch
        if: false # github.event_name == 'pull_request'
        run: brew tap https://github.com/gear-tech/homebrew-gear/tree/${{ github.ref_name }}

      - name: Add Gear tap from master
        if: true # github.event_name == 'push'
        run: brew tap gear-tech/gear

      - name: Test Gear formulae
        run: |
          brew install gear
          gear --version && [ "$(gear --version)" = "gear 0.1.6-92ca3911de2" ]
          brew rm gear
          for GV in $GEAR_VERSIONS; do
            brew install gear@$GV
            gear --version
            brew rm gear@$GV
          done

      - name: Test Vara formulae
        run: |
          brew install vara
          gear --version && [ "$(gear --version)" = "gear 0.1.6-78dfa07ed34" ]
          brew rm vara
          for VV in $VARA_VERSIONS; do
            brew install vara@$VV
            gear --version
            brew rm vara@$VV
          done
