name: Test

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    name: Test formulae
    strategy:
      fail-fast: false
      matrix:
        include:
          # Gear macOS formulae
          - os: macos-latest
            cmd: gear
            formula: gear

          - os: macos-latest
            cmd: gear
            formula: gear@nightly

          - os: macos-latest
            cmd: gear
            formula: gear@2.0.0

          - os: macos-latest
            cmd: gear
            formula: gear@1.10.0

          # Ethexe macOS formulae
          - os: macos-latest
            cmd: ethexe
            formula: ethexe

          - os: macos-latest
            cmd: ethexe
            formula: ethexe@nightly

          - os: macos-latest
            cmd: ethexe
            formula: ethexe@2.0.0

          # disabled due to `--version` not working for ethexe@1.10.0
          # - os: macos-latest
          #   cmd: ethexe
          #   formula: ethexe@1.10.0

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Add Gear tap from PR's branch
        if: github.event_name == 'pull_request'
        run: brew tap ${{ github.repository }} $GITHUB_WORKSPACE

      - name: Add Gear tap from master
        if: github.event_name == 'push'
        run: brew tap ${{ github.repository }}

      - name: Test formula
        run: |
          brew install ${{ matrix.formula }}
          ${{ matrix.cmd }} --version
