name: Test

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

env:
  GEAR_VERSIONS: 0.1.6 0.1.5 0.1.4 0.1.3 0.1.2 0.1.1
  VARA_VERSIONS: 1.1 1.0

jobs:
  test:
    name: Test formulae
    strategy:
      fail-fast: false
      matrix:
        include:
          # Gear macOS formulae
          - os: macOS-latest
            formula: gear

          - os: macOS-latest
            formula: gear@0.1.6

          - os: macOS-latest
            formula: gear@0.1.5

          - os: macOS-latest
            formula: gear@0.1.4

          - os: macOS-latest
            formula: gear@0.1.3

          - os: macOS-latest
            formula: gear@0.1.2

          - os: macOS-latest
            formula: gear@0.1.1

          # Vara macOS formulae
          - os: macOS-latest
            formula: vara

          - os: macOS-latest
            formula: vara@1.1

          - os: macOS-latest
            formula: vara@1.0

    runs-on: ${{ matrix.os }}

    steps:
      # Not used but let's keep it for now
      - name: Install brew on Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh | bash
          echo "/home/linuxbrew/.linuxbrew/bin" >> $GITHUB_PATH
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          (echo; echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"') >> $HOME/.bash_profile
          (echo; echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"') >> $HOME/.profile
          brew install hello

      # TODO: Find a solution to add a tap from a PR's branch
      - name: Add Gear tap from PR's branch
        if: false # github.event_name == 'pull_request'
        run: brew tap https://github.com/gear-tech/homebrew-gear/tree/${{ github.ref_name }}

      - name: Add Gear tap from master
        if: true # github.event_name == 'push'
        run: brew tap gear-tech/gear

      - name: Test formula
        run: |
          brew install ${{ matrix.formula }}
